name: autoreview-by-label
description: Automatically adds a review in the presence of a label
author: EmbarkStudios
branding:
  icon: book-open
  color: purple
inputs:
  github-token:
    description: Github token for the account performing auto reviews
    default: ${{ github.token }}
  label-name:
    description: Label that will trigger auto review (reviews will be removed if the label isn't present)
  bot-username:
    description: Github nick name for the bot account, used to remove previous comments
runs:
  using: node16
  main: dist/index.js
