import {parseGithubLabelEvent} from '../src/types/githubEvent';

const input = `{
    "action": "labeled",
    "label": {
      "color": "d73a4a",
      "default": true,
      "description": "Something isn't working",
      "id": 5209427085,
      "name": "bug",
      "node_id": "LA_kwDOJDnt-M8AAAABNoGMjQ",
      "url": "https://api.github.com/repos/thefuntastic/actions_test/labels/bug"
    },
    "number": 1,
    "pull_request": {
      "_links": {
        "comments": {
          "href": "https://api.github.com/repos/thefuntastic/actions_test/issues/1/comments"
        },
        "commits": {
          "href": "https://api.github.com/repos/thefuntastic/actions_test/pulls/1/commits"
        },
        "html": {
          "href": "https://github.com/thefuntastic/actions_test/pull/1"
        },
        "issue": {
          "href": "https://api.github.com/repos/thefuntastic/actions_test/issues/1"
        },
        "review_comment": {
          "href": "https://api.github.com/repos/thefuntastic/actions_test/pulls/comments{/number}"
        },
        "review_comments": {
          "href": "https://api.github.com/repos/thefuntastic/actions_test/pulls/1/comments"
        },
        "self": {
          "href": "https://api.github.com/repos/thefuntastic/actions_test/pulls/1"
        },
        "statuses": {
          "href": "https://api.github.com/repos/thefuntastic/actions_test/statuses/13be915e5fac39e5d929287a252bbdc0b69b2c2d"
        }
      },
      "active_lock_reason": null,
      "additions": 4,
      "assignee": null,
      "assignees": [],
      "author_association": "OWNER",
      "auto_merge": null,
      "base": {
        "label": "thefuntastic:main",
        "ref": "main",
        "repo": {
          "allow_auto_merge": false,
          "allow_forking": true,
          "allow_merge_commit": true,
          "allow_rebase_merge": true,
          "allow_squash_merge": true,
          "allow_update_branch": false,
          "archive_url": "https://api.github.com/repos/thefuntastic/actions_test/{archive_format}{/ref}",
          "archived": false,
          "assignees_url": "https://api.github.com/repos/thefuntastic/actions_test/assignees{/user}",
          "blobs_url": "https://api.github.com/repos/thefuntastic/actions_test/git/blobs{/sha}",
          "branches_url": "https://api.github.com/repos/thefuntastic/actions_test/branches{/branch}",
          "clone_url": "https://github.com/thefuntastic/actions_test.git",
          "collaborators_url": "https://api.github.com/repos/thefuntastic/actions_test/collaborators{/collaborator}",
          "comments_url": "https://api.github.com/repos/thefuntastic/actions_test/comments{/number}",
          "commits_url": "https://api.github.com/repos/thefuntastic/actions_test/commits{/sha}",
          "compare_url": "https://api.github.com/repos/thefuntastic/actions_test/compare/{base}...{head}",
          "contents_url": "https://api.github.com/repos/thefuntastic/actions_test/contents/{+path}",
          "contributors_url": "https://api.github.com/repos/thefuntastic/actions_test/contributors",
          "created_at": "2023-02-28T16:49:08Z",
          "default_branch": "main",
          "delete_branch_on_merge": false,
          "deployments_url": "https://api.github.com/repos/thefuntastic/actions_test/deployments",
          "description": "Dummy repo to test github actions",
          "disabled": false,
          "downloads_url": "https://api.github.com/repos/thefuntastic/actions_test/downloads",
          "events_url": "https://api.github.com/repos/thefuntastic/actions_test/events",
          "fork": false,
          "forks": 0,
          "forks_count": 0,
          "forks_url": "https://api.github.com/repos/thefuntastic/actions_test/forks",
          "full_name": "thefuntastic/actions_test",
          "git_commits_url": "https://api.github.com/repos/thefuntastic/actions_test/git/commits{/sha}",
          "git_refs_url": "https://api.github.com/repos/thefuntastic/actions_test/git/refs{/sha}",
          "git_tags_url": "https://api.github.com/repos/thefuntastic/actions_test/git/tags{/sha}",
          "git_url": "git://github.com/thefuntastic/actions_test.git",
          "has_discussions": false,
          "has_downloads": true,
          "has_issues": true,
          "has_pages": false,
          "has_projects": true,
          "has_wiki": true,
          "homepage": null,
          "hooks_url": "https://api.github.com/repos/thefuntastic/actions_test/hooks",
          "html_url": "https://github.com/thefuntastic/actions_test",
          "id": 607776248,
          "is_template": false,
          "issue_comment_url": "https://api.github.com/repos/thefuntastic/actions_test/issues/comments{/number}",
          "issue_events_url": "https://api.github.com/repos/thefuntastic/actions_test/issues/events{/number}",
          "issues_url": "https://api.github.com/repos/thefuntastic/actions_test/issues{/number}",
          "keys_url": "https://api.github.com/repos/thefuntastic/actions_test/keys{/key_id}",
          "labels_url": "https://api.github.com/repos/thefuntastic/actions_test/labels{/name}",
          "language": "Rust",
          "languages_url": "https://api.github.com/repos/thefuntastic/actions_test/languages",
          "license": null,
          "merge_commit_message": "PR_TITLE",
          "merge_commit_title": "MERGE_MESSAGE",
          "merges_url": "https://api.github.com/repos/thefuntastic/actions_test/merges",
          "milestones_url": "https://api.github.com/repos/thefuntastic/actions_test/milestones{/number}",
          "mirror_url": null,
          "name": "actions_test",
          "node_id": "R_kgDOJDnt-A",
          "notifications_url": "https://api.github.com/repos/thefuntastic/actions_test/notifications{?since,all,participating}",
          "open_issues": 1,
          "open_issues_count": 1,
          "owner": {
            "avatar_url": "https://avatars.githubusercontent.com/u/296286?v=4",
            "events_url": "https://api.github.com/users/thefuntastic/events{/privacy}",
            "followers_url": "https://api.github.com/users/thefuntastic/followers",
            "following_url": "https://api.github.com/users/thefuntastic/following{/other_user}",
            "gists_url": "https://api.github.com/users/thefuntastic/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/thefuntastic",
            "id": 296286,
            "login": "thefuntastic",
            "node_id": "MDQ6VXNlcjI5NjI4Ng==",
            "organizations_url": "https://api.github.com/users/thefuntastic/orgs",
            "received_events_url": "https://api.github.com/users/thefuntastic/received_events",
            "repos_url": "https://api.github.com/users/thefuntastic/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/thefuntastic/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/thefuntastic/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/thefuntastic"
          },
          "private": true,
          "pulls_url": "https://api.github.com/repos/thefuntastic/actions_test/pulls{/number}",
          "pushed_at": "2023-03-01T15:05:30Z",
          "releases_url": "https://api.github.com/repos/thefuntastic/actions_test/releases{/id}",
          "size": 4,
          "squash_merge_commit_message": "COMMIT_MESSAGES",
          "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
          "ssh_url": "git@github.com:thefuntastic/actions_test.git",
          "stargazers_count": 0,
          "stargazers_url": "https://api.github.com/repos/thefuntastic/actions_test/stargazers",
          "statuses_url": "https://api.github.com/repos/thefuntastic/actions_test/statuses/{sha}",
          "subscribers_url": "https://api.github.com/repos/thefuntastic/actions_test/subscribers",
          "subscription_url": "https://api.github.com/repos/thefuntastic/actions_test/subscription",
          "svn_url": "https://github.com/thefuntastic/actions_test",
          "tags_url": "https://api.github.com/repos/thefuntastic/actions_test/tags",
          "teams_url": "https://api.github.com/repos/thefuntastic/actions_test/teams",
          "topics": [],
          "trees_url": "https://api.github.com/repos/thefuntastic/actions_test/git/trees{/sha}",
          "updated_at": "2023-02-28T16:50:01Z",
          "url": "https://api.github.com/repos/thefuntastic/actions_test",
          "use_squash_pr_title_as_default": false,
          "visibility": "private",
          "watchers": 0,
          "watchers_count": 0,
          "web_commit_signoff_required": false
        },
        "sha": "555b42505b12a2a0a1fd9905b86fac56ea1bd001",
        "user": {
          "avatar_url": "https://avatars.githubusercontent.com/u/296286?v=4",
          "events_url": "https://api.github.com/users/thefuntastic/events{/privacy}",
          "followers_url": "https://api.github.com/users/thefuntastic/followers",
          "following_url": "https://api.github.com/users/thefuntastic/following{/other_user}",
          "gists_url": "https://api.github.com/users/thefuntastic/gists{/gist_id}",
          "gravatar_id": "",
          "html_url": "https://github.com/thefuntastic",
          "id": 296286,
          "login": "thefuntastic",
          "node_id": "MDQ6VXNlcjI5NjI4Ng==",
          "organizations_url": "https://api.github.com/users/thefuntastic/orgs",
          "received_events_url": "https://api.github.com/users/thefuntastic/received_events",
          "repos_url": "https://api.github.com/users/thefuntastic/repos",
          "site_admin": false,
          "starred_url": "https://api.github.com/users/thefuntastic/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/thefuntastic/subscriptions",
          "type": "User",
          "url": "https://api.github.com/users/thefuntastic"
        }
      },
      "body": "Test test",
      "changed_files": 1,
      "closed_at": null,
      "comments": 0,
      "comments_url": "https://api.github.com/repos/thefuntastic/actions_test/issues/1/comments",
      "commits": 1,
      "commits_url": "https://api.github.com/repos/thefuntastic/actions_test/pulls/1/commits",
      "created_at": "2023-02-28T17:19:08Z",
      "deletions": 0,
      "diff_url": "https://github.com/thefuntastic/actions_test/pull/1.diff",
      "draft": false,
      "head": {
        "label": "thefuntastic:test_pr",
        "ref": "test_pr",
        "repo": {
          "allow_auto_merge": false,
          "allow_forking": true,
          "allow_merge_commit": true,
          "allow_rebase_merge": true,
          "allow_squash_merge": true,
          "allow_update_branch": false,
          "archive_url": "https://api.github.com/repos/thefuntastic/actions_test/{archive_format}{/ref}",
          "archived": false,
          "assignees_url": "https://api.github.com/repos/thefuntastic/actions_test/assignees{/user}",
          "blobs_url": "https://api.github.com/repos/thefuntastic/actions_test/git/blobs{/sha}",
          "branches_url": "https://api.github.com/repos/thefuntastic/actions_test/branches{/branch}",
          "clone_url": "https://github.com/thefuntastic/actions_test.git",
          "collaborators_url": "https://api.github.com/repos/thefuntastic/actions_test/collaborators{/collaborator}",
          "comments_url": "https://api.github.com/repos/thefuntastic/actions_test/comments{/number}",
          "commits_url": "https://api.github.com/repos/thefuntastic/actions_test/commits{/sha}",
          "compare_url": "https://api.github.com/repos/thefuntastic/actions_test/compare/{base}...{head}",
          "contents_url": "https://api.github.com/repos/thefuntastic/actions_test/contents/{+path}",
          "contributors_url": "https://api.github.com/repos/thefuntastic/actions_test/contributors",
          "created_at": "2023-02-28T16:49:08Z",
          "default_branch": "main",
          "delete_branch_on_merge": false,
          "deployments_url": "https://api.github.com/repos/thefuntastic/actions_test/deployments",
          "description": "Dummy repo to test github actions",
          "disabled": false,
          "downloads_url": "https://api.github.com/repos/thefuntastic/actions_test/downloads",
          "events_url": "https://api.github.com/repos/thefuntastic/actions_test/events",
          "fork": false,
          "forks": 0,
          "forks_count": 0,
          "forks_url": "https://api.github.com/repos/thefuntastic/actions_test/forks",
          "full_name": "thefuntastic/actions_test",
          "git_commits_url": "https://api.github.com/repos/thefuntastic/actions_test/git/commits{/sha}",
          "git_refs_url": "https://api.github.com/repos/thefuntastic/actions_test/git/refs{/sha}",
          "git_tags_url": "https://api.github.com/repos/thefuntastic/actions_test/git/tags{/sha}",
          "git_url": "git://github.com/thefuntastic/actions_test.git",
          "has_discussions": false,
          "has_downloads": true,
          "has_issues": true,
          "has_pages": false,
          "has_projects": true,
          "has_wiki": true,
          "homepage": null,
          "hooks_url": "https://api.github.com/repos/thefuntastic/actions_test/hooks",
          "html_url": "https://github.com/thefuntastic/actions_test",
          "id": 607776248,
          "is_template": false,
          "issue_comment_url": "https://api.github.com/repos/thefuntastic/actions_test/issues/comments{/number}",
          "issue_events_url": "https://api.github.com/repos/thefuntastic/actions_test/issues/events{/number}",
          "issues_url": "https://api.github.com/repos/thefuntastic/actions_test/issues{/number}",
          "keys_url": "https://api.github.com/repos/thefuntastic/actions_test/keys{/key_id}",
          "labels_url": "https://api.github.com/repos/thefuntastic/actions_test/labels{/name}",
          "language": "Rust",
          "languages_url": "https://api.github.com/repos/thefuntastic/actions_test/languages",
          "license": null,
          "merge_commit_message": "PR_TITLE",
          "merge_commit_title": "MERGE_MESSAGE",
          "merges_url": "https://api.github.com/repos/thefuntastic/actions_test/merges",
          "milestones_url": "https://api.github.com/repos/thefuntastic/actions_test/milestones{/number}",
          "mirror_url": null,
          "name": "actions_test",
          "node_id": "R_kgDOJDnt-A",
          "notifications_url": "https://api.github.com/repos/thefuntastic/actions_test/notifications{?since,all,participating}",
          "open_issues": 1,
          "open_issues_count": 1,
          "owner": {
            "avatar_url": "https://avatars.githubusercontent.com/u/296286?v=4",
            "events_url": "https://api.github.com/users/thefuntastic/events{/privacy}",
            "followers_url": "https://api.github.com/users/thefuntastic/followers",
            "following_url": "https://api.github.com/users/thefuntastic/following{/other_user}",
            "gists_url": "https://api.github.com/users/thefuntastic/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/thefuntastic",
            "id": 296286,
            "login": "thefuntastic",
            "node_id": "MDQ6VXNlcjI5NjI4Ng==",
            "organizations_url": "https://api.github.com/users/thefuntastic/orgs",
            "received_events_url": "https://api.github.com/users/thefuntastic/received_events",
            "repos_url": "https://api.github.com/users/thefuntastic/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/thefuntastic/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/thefuntastic/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/thefuntastic"
          },
          "private": true,
          "pulls_url": "https://api.github.com/repos/thefuntastic/actions_test/pulls{/number}",
          "pushed_at": "2023-03-01T15:05:30Z",
          "releases_url": "https://api.github.com/repos/thefuntastic/actions_test/releases{/id}",
          "size": 4,
          "squash_merge_commit_message": "COMMIT_MESSAGES",
          "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
          "ssh_url": "git@github.com:thefuntastic/actions_test.git",
          "stargazers_count": 0,
          "stargazers_url": "https://api.github.com/repos/thefuntastic/actions_test/stargazers",
          "statuses_url": "https://api.github.com/repos/thefuntastic/actions_test/statuses/{sha}",
          "subscribers_url": "https://api.github.com/repos/thefuntastic/actions_test/subscribers",
          "subscription_url": "https://api.github.com/repos/thefuntastic/actions_test/subscription",
          "svn_url": "https://github.com/thefuntastic/actions_test",
          "tags_url": "https://api.github.com/repos/thefuntastic/actions_test/tags",
          "teams_url": "https://api.github.com/repos/thefuntastic/actions_test/teams",
          "topics": [],
          "trees_url": "https://api.github.com/repos/thefuntastic/actions_test/git/trees{/sha}",
          "updated_at": "2023-02-28T16:50:01Z",
          "url": "https://api.github.com/repos/thefuntastic/actions_test",
          "use_squash_pr_title_as_default": false,
          "visibility": "private",
          "watchers": 0,
          "watchers_count": 0,
          "web_commit_signoff_required": false
        },
        "sha": "13be915e5fac39e5d929287a252bbdc0b69b2c2d",
        "user": {
          "avatar_url": "https://avatars.githubusercontent.com/u/296286?v=4",
          "events_url": "https://api.github.com/users/thefuntastic/events{/privacy}",
          "followers_url": "https://api.github.com/users/thefuntastic/followers",
          "following_url": "https://api.github.com/users/thefuntastic/following{/other_user}",
          "gists_url": "https://api.github.com/users/thefuntastic/gists{/gist_id}",
          "gravatar_id": "",
          "html_url": "https://github.com/thefuntastic",
          "id": 296286,
          "login": "thefuntastic",
          "node_id": "MDQ6VXNlcjI5NjI4Ng==",
          "organizations_url": "https://api.github.com/users/thefuntastic/orgs",
          "received_events_url": "https://api.github.com/users/thefuntastic/received_events",
          "repos_url": "https://api.github.com/users/thefuntastic/repos",
          "site_admin": false,
          "starred_url": "https://api.github.com/users/thefuntastic/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/thefuntastic/subscriptions",
          "type": "User",
          "url": "https://api.github.com/users/thefuntastic"
        }
      },
      "html_url": "https://github.com/thefuntastic/actions_test/pull/1",
      "id": 1257494916,
      "issue_url": "https://api.github.com/repos/thefuntastic/actions_test/issues/1",
      "labels": [
        {
          "color": "d73a4a",
          "default": true,
          "description": "Something isn't working",
          "id": 5209427085,
          "name": "bug",
          "node_id": "LA_kwDOJDnt-M8AAAABNoGMjQ",
          "url": "https://api.github.com/repos/thefuntastic/actions_test/labels/bug"
        }
      ],
      "locked": false,
      "maintainer_can_modify": false,
      "merge_commit_sha": "693f5ece0d469359e5e131a6d83dd012634767f9",
      "mergeable": true,
      "mergeable_state": "clean",
      "merged": false,
      "merged_at": null,
      "merged_by": null,
      "milestone": null,
      "node_id": "PR_kwDOJDnt-M5K89mE",
      "number": 1,
      "patch_url": "https://github.com/thefuntastic/actions_test/pull/1.patch",
      "rebaseable": true,
      "requested_reviewers": [],
      "requested_teams": [],
      "review_comment_url": "https://api.github.com/repos/thefuntastic/actions_test/pulls/comments{/number}",
      "review_comments": 0,
      "review_comments_url": "https://api.github.com/repos/thefuntastic/actions_test/pulls/1/comments",
      "state": "open",
      "statuses_url": "https://api.github.com/repos/thefuntastic/actions_test/statuses/13be915e5fac39e5d929287a252bbdc0b69b2c2d",
      "title": "PR no 1 ",
      "updated_at": "2023-03-01T15:24:40Z",
      "url": "https://api.github.com/repos/thefuntastic/actions_test/pulls/1",
      "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/296286?v=4",
        "events_url": "https://api.github.com/users/thefuntastic/events{/privacy}",
        "followers_url": "https://api.github.com/users/thefuntastic/followers",
        "following_url": "https://api.github.com/users/thefuntastic/following{/other_user}",
        "gists_url": "https://api.github.com/users/thefuntastic/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/thefuntastic",
        "id": 296286,
        "login": "thefuntastic",
        "node_id": "MDQ6VXNlcjI5NjI4Ng==",
        "organizations_url": "https://api.github.com/users/thefuntastic/orgs",
        "received_events_url": "https://api.github.com/users/thefuntastic/received_events",
        "repos_url": "https://api.github.com/users/thefuntastic/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/thefuntastic/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/thefuntastic/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/thefuntastic"
      }
    },
    "repository": {
      "allow_forking": true,
      "archive_url": "https://api.github.com/repos/thefuntastic/actions_test/{archive_format}{/ref}",
      "archived": false,
      "assignees_url": "https://api.github.com/repos/thefuntastic/actions_test/assignees{/user}",
      "blobs_url": "https://api.github.com/repos/thefuntastic/actions_test/git/blobs{/sha}",
      "branches_url": "https://api.github.com/repos/thefuntastic/actions_test/branches{/branch}",
      "clone_url": "https://github.com/thefuntastic/actions_test.git",
      "collaborators_url": "https://api.github.com/repos/thefuntastic/actions_test/collaborators{/collaborator}",
      "comments_url": "https://api.github.com/repos/thefuntastic/actions_test/comments{/number}",
      "commits_url": "https://api.github.com/repos/thefuntastic/actions_test/commits{/sha}",
      "compare_url": "https://api.github.com/repos/thefuntastic/actions_test/compare/{base}...{head}",
      "contents_url": "https://api.github.com/repos/thefuntastic/actions_test/contents/{+path}",
      "contributors_url": "https://api.github.com/repos/thefuntastic/actions_test/contributors",
      "created_at": "2023-02-28T16:49:08Z",
      "default_branch": "main",
      "deployments_url": "https://api.github.com/repos/thefuntastic/actions_test/deployments",
      "description": "Dummy repo to test github actions",
      "disabled": false,
      "downloads_url": "https://api.github.com/repos/thefuntastic/actions_test/downloads",
      "events_url": "https://api.github.com/repos/thefuntastic/actions_test/events",
      "fork": false,
      "forks": 0,
      "forks_count": 0,
      "forks_url": "https://api.github.com/repos/thefuntastic/actions_test/forks",
      "full_name": "thefuntastic/actions_test",
      "git_commits_url": "https://api.github.com/repos/thefuntastic/actions_test/git/commits{/sha}",
      "git_refs_url": "https://api.github.com/repos/thefuntastic/actions_test/git/refs{/sha}",
      "git_tags_url": "https://api.github.com/repos/thefuntastic/actions_test/git/tags{/sha}",
      "git_url": "git://github.com/thefuntastic/actions_test.git",
      "has_discussions": false,
      "has_downloads": true,
      "has_issues": true,
      "has_pages": false,
      "has_projects": true,
      "has_wiki": true,
      "homepage": null,
      "hooks_url": "https://api.github.com/repos/thefuntastic/actions_test/hooks",
      "html_url": "https://github.com/thefuntastic/actions_test",
      "id": 607776248,
      "is_template": false,
      "issue_comment_url": "https://api.github.com/repos/thefuntastic/actions_test/issues/comments{/number}",
      "issue_events_url": "https://api.github.com/repos/thefuntastic/actions_test/issues/events{/number}",
      "issues_url": "https://api.github.com/repos/thefuntastic/actions_test/issues{/number}",
      "keys_url": "https://api.github.com/repos/thefuntastic/actions_test/keys{/key_id}",
      "labels_url": "https://api.github.com/repos/thefuntastic/actions_test/labels{/name}",
      "language": "Rust",
      "languages_url": "https://api.github.com/repos/thefuntastic/actions_test/languages",
      "license": null,
      "merges_url": "https://api.github.com/repos/thefuntastic/actions_test/merges",
      "milestones_url": "https://api.github.com/repos/thefuntastic/actions_test/milestones{/number}",
      "mirror_url": null,
      "name": "actions_test",
      "node_id": "R_kgDOJDnt-A",
      "notifications_url": "https://api.github.com/repos/thefuntastic/actions_test/notifications{?since,all,participating}",
      "open_issues": 1,
      "open_issues_count": 1,
      "owner": {
        "avatar_url": "https://avatars.githubusercontent.com/u/296286?v=4",
        "events_url": "https://api.github.com/users/thefuntastic/events{/privacy}",
        "followers_url": "https://api.github.com/users/thefuntastic/followers",
        "following_url": "https://api.github.com/users/thefuntastic/following{/other_user}",
        "gists_url": "https://api.github.com/users/thefuntastic/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/thefuntastic",
        "id": 296286,
        "login": "thefuntastic",
        "node_id": "MDQ6VXNlcjI5NjI4Ng==",
        "organizations_url": "https://api.github.com/users/thefuntastic/orgs",
        "received_events_url": "https://api.github.com/users/thefuntastic/received_events",
        "repos_url": "https://api.github.com/users/thefuntastic/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/thefuntastic/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/thefuntastic/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/thefuntastic"
      },
      "private": true,
      "pulls_url": "https://api.github.com/repos/thefuntastic/actions_test/pulls{/number}",
      "pushed_at": "2023-03-01T15:05:30Z",
      "releases_url": "https://api.github.com/repos/thefuntastic/actions_test/releases{/id}",
      "size": 4,
      "ssh_url": "git@github.com:thefuntastic/actions_test.git",
      "stargazers_count": 0,
      "stargazers_url": "https://api.github.com/repos/thefuntastic/actions_test/stargazers",
      "statuses_url": "https://api.github.com/repos/thefuntastic/actions_test/statuses/{sha}",
      "subscribers_url": "https://api.github.com/repos/thefuntastic/actions_test/subscribers",
      "subscription_url": "https://api.github.com/repos/thefuntastic/actions_test/subscription",
      "svn_url": "https://github.com/thefuntastic/actions_test",
      "tags_url": "https://api.github.com/repos/thefuntastic/actions_test/tags",
      "teams_url": "https://api.github.com/repos/thefuntastic/actions_test/teams",
      "topics": [],
      "trees_url": "https://api.github.com/repos/thefuntastic/actions_test/git/trees{/sha}",
      "updated_at": "2023-02-28T16:50:01Z",
      "url": "https://api.github.com/repos/thefuntastic/actions_test",
      "visibility": "private",
      "watchers": 0,
      "watchers_count": 0,
      "web_commit_signoff_required": false
    },
    "sender": {
      "avatar_url": "https://avatars.githubusercontent.com/u/296286?v=4",
      "events_url": "https://api.github.com/users/thefuntastic/events{/privacy}",
      "followers_url": "https://api.github.com/users/thefuntastic/followers",
      "following_url": "https://api.github.com/users/thefuntastic/following{/other_user}",
      "gists_url": "https://api.github.com/users/thefuntastic/gists{/gist_id}",
      "gravatar_id": "",
      "html_url": "https://github.com/thefuntastic",
      "id": 296286,
      "login": "thefuntastic",
      "node_id": "MDQ6VXNlcjI5NjI4Ng==",
      "organizations_url": "https://api.github.com/users/thefuntastic/orgs",
      "received_events_url": "https://api.github.com/users/thefuntastic/received_events",
      "repos_url": "https://api.github.com/users/thefuntastic/repos",
      "site_admin": false,
      "starred_url": "https://api.github.com/users/thefuntastic/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thefuntastic/subscriptions",
      "type": "User",
      "url": "https://api.github.com/users/thefuntastic"
    }
  }`;

const inputMinified = `{
  "action": "labeled",
  "label": {
    "color": "d73a4a",
    "default": true,
    "description": "Something isn't working",
    "id": 5209427085,
    "name": "bug",
    "url": "https://api.github.com/repos/thefuntastic/actions_test/labels/bug"
  },
  "pull_request": {
    "body": "Test test",
    "id": 123456,
    "labels": [
      {
        "color": "d73a4a",
        "default": true,
        "description": "Something isn't working",
        "id": 5209427085,
        "name": "bug",
        "url": "https://api.github.com/repos/thefuntastic/actions_test/labels/bug"
      }
    ],
    "number": 1,
    "title": "PR no 1 "
  },
  "repository": {
    "name": "actions_test",
    "owner": {
      "login": "thefuntastic"
    }
  }
}`;

test('Postive case', () => {
  const data = parseGithubLabelEvent(inputMinified);

  expect(data.action).toEqual('labeled');
});
